<?php

namespace Database\Seeders;

use App\Models\Influencer;
use Illuminate\Database\Seeder;

class InfluencerPortugalSeeder extends Seeder
{
    public function run(): void
    {
        $userId = 1;

        $influencers = [
            // ── GRANDES CRIADORES ────────────────────────────────────────────
            [
                'name' => 'Drift0r PT (DriftKing)',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@DriftKingPT',
                'instagram' => '@driftkingpt',
                'niche' => 'fps,general_gaming,tips',
                'subscribers' => 180000,
                'avg_views' => 22000,
                'engagement_rate' => 5.8,
                'status' => 'prospect',
                'tags' => ['fps', 'gaming', 'portugal'],
            ],
            [
                'name' => 'Pipoca com Manteiga',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@PipocacomManteiga',
                'instagram' => '@pipocacommanteiga',
                'twitter' => '@pipocacommanteiga',
                'niche' => 'game_review,movies,geek',
                'subscribers' => 320000,
                'avg_views' => 40000,
                'engagement_rate' => 5.5,
                'status' => 'prospect',
                'tags' => ['review', 'geek', 'filmes', 'games', 'portugal'],
            ],
            [
                'name' => 'Furacão Gamer',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@FuracaoGamer',
                'instagram' => '@furacaogamer',
                'niche' => 'general_gaming,fps,letsplay',
                'subscribers' => 260000,
                'avg_views' => 32000,
                'engagement_rate' => 5.2,
                'status' => 'prospect',
                'tags' => ['gaming', 'fps', 'let\'s play', 'portugal'],
            ],
            [
                'name' => 'Gameplays PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@GameplaysPT',
                'instagram' => '@gameplayspt',
                'niche' => 'letsplay,general_gaming,adventure',
                'subscribers' => 195000,
                'avg_views' => 24000,
                'engagement_rate' => 5.0,
                'status' => 'prospect',
                'tags' => ['let\'s play', 'gaming', 'aventura', 'portugal'],
            ],
            [
                'name' => 'Nerd Maneiro PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@NerdManeiroPT',
                'instagram' => '@nerdmaneiropt',
                'niche' => 'geek,game_review,anime',
                'subscribers' => 145000,
                'avg_views' => 18000,
                'engagement_rate' => 5.8,
                'status' => 'prospect',
                'tags' => ['geek', 'review', 'anime', 'games', 'portugal'],
            ],
            [
                'name' => 'Hugo Cunha',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@HugoCunha',
                'instagram' => '@hugocunha',
                'niche' => 'general_gaming,fps,review',
                'subscribers' => 210000,
                'avg_views' => 26000,
                'engagement_rate' => 5.3,
                'status' => 'prospect',
                'tags' => ['gaming', 'fps', 'review', 'portugal'],
            ],
            [
                'name' => 'Diogo Faria',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@DiogoFariaGames',
                'instagram' => '@diogofariagames',
                'niche' => 'general_gaming,adventure,rpg',
                'subscribers' => 175000,
                'avg_views' => 21000,
                'engagement_rate' => 5.6,
                'status' => 'prospect',
                'tags' => ['gaming', 'rpg', 'aventura', 'portugal'],
            ],
            [
                'name' => 'Ruben Ramos Gaming',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@RubenRamosGaming',
                'instagram' => '@rubenramosgaming',
                'niche' => 'general_gaming,fps,esports',
                'subscribers' => 155000,
                'avg_views' => 19000,
                'engagement_rate' => 5.4,
                'status' => 'prospect',
                'tags' => ['gaming', 'fps', 'esports', 'portugal'],
            ],
            [
                'name' => 'Tiago Fernandes Games',
                'type' => 'streamer',
                'channel_url' => 'https://www.youtube.com/@TiagoFernandesGames',
                'instagram' => '@tiagofgames',
                'niche' => 'general_gaming,minecraft,letsplay',
                'subscribers' => 132000,
                'avg_views' => 16000,
                'engagement_rate' => 5.7,
                'status' => 'prospect',
                'tags' => ['gaming', 'minecraft', 'let\'s play', 'portugal'],
            ],
            [
                'name' => 'GamerBoy PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@GamerBoyPT',
                'instagram' => '@gamerboyPT',
                'niche' => 'general_gaming,tips,review',
                'subscribers' => 120000,
                'avg_views' => 15000,
                'engagement_rate' => 5.5,
                'status' => 'prospect',
                'tags' => ['gaming', 'dicas', 'review', 'portugal'],
            ],

            // ── GAME DEV / INDIE PORTUGAL ────────────────────────────────────
            [
                'name' => 'Bruno Oliveira Dev',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@BrunoOliveiraDev',
                'instagram' => '@brunooliveira.dev',
                'niche' => 'game_dev,unity,tutorial',
                'subscribers' => 48000,
                'avg_views' => 6500,
                'engagement_rate' => 7.5,
                'status' => 'prospect',
                'tags' => ['game dev', 'unity', 'tutorial', 'portugal'],
            ],
            [
                'name' => 'GameDev Portugal',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@GameDevPortugal',
                'instagram' => '@gamedevportugal',
                'niche' => 'game_dev,indie,community',
                'subscribers' => 35000,
                'avg_views' => 4800,
                'engagement_rate' => 7.8,
                'status' => 'prospect',
                'tags' => ['game dev', 'indie', 'comunidade', 'portugal'],
            ],
            [
                'name' => 'Indie PT Studio',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@IndiePTStudio',
                'instagram' => '@indieptstudio',
                'niche' => 'indie,game_dev,devlog',
                'subscribers' => 28000,
                'avg_views' => 3900,
                'engagement_rate' => 8.0,
                'status' => 'prospect',
                'tags' => ['indie', 'devlog', 'game dev', 'portugal'],
            ],
            [
                'name' => 'João Santos Dev',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@JoaoSantosDev',
                'instagram' => '@joaosantosdev',
                'niche' => 'game_dev,godot,tutorial',
                'subscribers' => 22000,
                'avg_views' => 3200,
                'engagement_rate' => 8.2,
                'status' => 'prospect',
                'tags' => ['godot', 'game dev', 'tutorial', 'portugal'],
            ],
            [
                'name' => 'Pedro Almeida Gamedev',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@PedroAlmeidaGamedev',
                'instagram' => '@pedroalmeidagamedev',
                'niche' => 'game_dev,unity,indie',
                'subscribers' => 18000,
                'avg_views' => 2600,
                'engagement_rate' => 7.9,
                'status' => 'prospect',
                'tags' => ['unity', 'indie', 'game dev', 'portugal'],
            ],
            [
                'name' => 'Lisbon Game Dev',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@LisbonGameDev',
                'instagram' => '@lisbongamedev',
                'niche' => 'game_dev,community,indie',
                'subscribers' => 15000,
                'avg_views' => 2200,
                'engagement_rate' => 8.1,
                'status' => 'prospect',
                'tags' => ['game dev', 'lisboa', 'comunidade', 'indie'],
            ],
            [
                'name' => 'Pixel Factory PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@PixelFactoryPT',
                'instagram' => '@pixelfactorypt',
                'niche' => 'pixel_art,game_dev,indie',
                'subscribers' => 24000,
                'avg_views' => 3400,
                'engagement_rate' => 7.6,
                'status' => 'prospect',
                'tags' => ['pixel art', 'indie', 'game dev', 'portugal'],
            ],
            [
                'name' => 'André Sousa Dev',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@AndreSousaDev',
                'instagram' => '@andresousadev',
                'niche' => 'game_dev,unreal,tutorial',
                'subscribers' => 19000,
                'avg_views' => 2800,
                'engagement_rate' => 7.7,
                'status' => 'prospect',
                'tags' => ['unreal engine', 'game dev', 'tutorial', 'portugal'],
            ],
            [
                'name' => 'PortoGameDev',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@PortoGameDev',
                'instagram' => '@portogamedev',
                'niche' => 'game_dev,indie,jam',
                'subscribers' => 12000,
                'avg_views' => 1800,
                'engagement_rate' => 8.3,
                'status' => 'prospect',
                'tags' => ['game dev', 'porto', 'game jam', 'indie'],
            ],
            [
                'name' => 'Mário Costa Indie',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@MarioCostalndie',
                'instagram' => '@mariocostaindie',
                'niche' => 'indie,devlog,game_dev',
                'subscribers' => 16500,
                'avg_views' => 2400,
                'engagement_rate' => 8.0,
                'status' => 'prospect',
                'tags' => ['indie', 'devlog', 'game dev', 'portugal'],
            ],

            // ── STREAMERS / FPS / ESPORTS ────────────────────────────────────
            [
                'name' => 'xBufer',
                'type' => 'streamer',
                'channel_url' => 'https://www.youtube.com/@xBufer',
                'instagram' => '@xbufer',
                'niche' => 'fps,cs2,esports',
                'subscribers' => 98000,
                'avg_views' => 12000,
                'engagement_rate' => 5.8,
                'status' => 'prospect',
                'tags' => ['cs2', 'fps', 'esports', 'portugal'],
            ],
            [
                'name' => 'Vini PT Gamer',
                'type' => 'streamer',
                'channel_url' => 'https://www.youtube.com/@ViniPTGamer',
                'instagram' => '@viniptgamer',
                'niche' => 'fps,valorant,esports',
                'subscribers' => 85000,
                'avg_views' => 10500,
                'engagement_rate' => 6.0,
                'status' => 'prospect',
                'tags' => ['valorant', 'fps', 'esports', 'portugal'],
            ],
            [
                'name' => 'Fábio Silva Gamer',
                'type' => 'streamer',
                'channel_url' => 'https://www.youtube.com/@FabioSilvaGamer',
                'instagram' => '@fabiosilva.gamer',
                'niche' => 'general_gaming,fps,streaming',
                'subscribers' => 72000,
                'avg_views' => 9000,
                'engagement_rate' => 5.9,
                'status' => 'prospect',
                'tags' => ['gaming', 'fps', 'streaming', 'portugal'],
            ],
            [
                'name' => 'NightOwl PT',
                'type' => 'streamer',
                'channel_url' => 'https://www.youtube.com/@NightOwlPT',
                'instagram' => '@nightowlpt',
                'niche' => 'horror,rpg,streaming',
                'subscribers' => 64000,
                'avg_views' => 8000,
                'engagement_rate' => 6.3,
                'status' => 'prospect',
                'tags' => ['horror', 'rpg', 'streaming', 'portugal'],
            ],
            [
                'name' => 'Miguel Ferreira Stream',
                'type' => 'streamer',
                'channel_url' => 'https://www.youtube.com/@MiguelFerreiraStream',
                'instagram' => '@miguelferreirastream',
                'niche' => 'fps,cs2,general_gaming',
                'subscribers' => 58000,
                'avg_views' => 7200,
                'engagement_rate' => 5.7,
                'status' => 'prospect',
                'tags' => ['cs2', 'fps', 'gaming', 'portugal'],
            ],
            [
                'name' => 'Luís Gamer PT',
                'type' => 'streamer',
                'channel_url' => 'https://www.youtube.com/@LuisGamerPT',
                'instagram' => '@luisgamerpt',
                'niche' => 'general_gaming,adventure,variety',
                'subscribers' => 52000,
                'avg_views' => 6500,
                'engagement_rate' => 6.1,
                'status' => 'prospect',
                'tags' => ['gaming', 'aventura', 'variedades', 'portugal'],
            ],
            [
                'name' => 'Carlos Mendes Gaming',
                'type' => 'streamer',
                'channel_url' => 'https://www.youtube.com/@CarlosMendesGaming',
                'instagram' => '@carlosmendesgaming',
                'niche' => 'fps,battle_royale,mobile',
                'subscribers' => 47000,
                'avg_views' => 5800,
                'engagement_rate' => 5.9,
                'status' => 'prospect',
                'tags' => ['fps', 'battle royale', 'mobile', 'portugal'],
            ],
            [
                'name' => 'DarkHero PT',
                'type' => 'streamer',
                'channel_url' => 'https://www.youtube.com/@DarkHeroPT',
                'instagram' => '@darkheropt',
                'niche' => 'rpg,soulslike,dark',
                'subscribers' => 43000,
                'avg_views' => 5500,
                'engagement_rate' => 6.5,
                'status' => 'prospect',
                'tags' => ['rpg', 'soulslike', 'dark fantasy', 'portugal'],
            ],
            [
                'name' => 'Ricardo Neto Games',
                'type' => 'streamer',
                'channel_url' => 'https://www.youtube.com/@RicardoNetoGames',
                'instagram' => '@ricardonetogames',
                'niche' => 'general_gaming,fps,comedy',
                'subscribers' => 39000,
                'avg_views' => 4900,
                'engagement_rate' => 6.0,
                'status' => 'prospect',
                'tags' => ['gaming', 'fps', 'humor', 'portugal'],
            ],
            [
                'name' => 'Bernardo Lopes Stream',
                'type' => 'streamer',
                'channel_url' => 'https://www.youtube.com/@BernardoLopesStream',
                'instagram' => '@bernardolopes.stream',
                'niche' => 'moba,lol,esports',
                'subscribers' => 36000,
                'avg_views' => 4500,
                'engagement_rate' => 5.8,
                'status' => 'prospect',
                'tags' => ['league of legends', 'moba', 'esports', 'portugal'],
            ],

            // ── MINECRAFT / SURVIVAL ────────────────────────────────────────
            [
                'name' => 'Craft PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@CraftPT',
                'instagram' => '@craftpt',
                'niche' => 'minecraft,survival,kids',
                'subscribers' => 155000,
                'avg_views' => 19000,
                'engagement_rate' => 5.5,
                'status' => 'prospect',
                'tags' => ['minecraft', 'survival', 'portugal'],
            ],
            [
                'name' => 'MinecraftPT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@MinecraftPT',
                'instagram' => '@minecraftpt',
                'niche' => 'minecraft,builds,tutorial',
                'subscribers' => 128000,
                'avg_views' => 16000,
                'engagement_rate' => 5.7,
                'status' => 'prospect',
                'tags' => ['minecraft', 'builds', 'tutorial', 'portugal'],
            ],
            [
                'name' => 'Tobias Games PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@TobiasGamesPT',
                'instagram' => '@tobiasgamespt',
                'niche' => 'minecraft,adventure,kids',
                'subscribers' => 112000,
                'avg_views' => 14000,
                'engagement_rate' => 5.9,
                'status' => 'prospect',
                'tags' => ['minecraft', 'aventura', 'kids', 'portugal'],
            ],
            [
                'name' => 'BloxPT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@BloxPT',
                'instagram' => '@bloxpt',
                'niche' => 'roblox,minecraft,kids',
                'subscribers' => 98000,
                'avg_views' => 12000,
                'engagement_rate' => 6.1,
                'status' => 'prospect',
                'tags' => ['roblox', 'minecraft', 'kids', 'portugal'],
            ],

            // ── RPG / NARRATIVE / ADVENTURE ─────────────────────────────────
            [
                'name' => 'RPG Nation PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@RPGNationPT',
                'instagram' => '@rpgnationpt',
                'niche' => 'rpg,narrative,adventure',
                'subscribers' => 87000,
                'avg_views' => 11000,
                'engagement_rate' => 6.2,
                'status' => 'prospect',
                'tags' => ['rpg', 'narrativa', 'aventura', 'portugal'],
            ],
            [
                'name' => 'Saga PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@SagaPT',
                'instagram' => '@sagapt',
                'niche' => 'rpg,lore,gaming',
                'subscribers' => 74000,
                'avg_views' => 9500,
                'engagement_rate' => 6.0,
                'status' => 'prospect',
                'tags' => ['rpg', 'lore', 'gaming', 'portugal'],
            ],
            [
                'name' => 'Dungeons PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@DungeonsPT',
                'instagram' => '@dungeonspt',
                'niche' => 'rpg,dnd,tabletop',
                'subscribers' => 62000,
                'avg_views' => 8000,
                'engagement_rate' => 6.5,
                'status' => 'prospect',
                'tags' => ['rpg', 'd&d', 'tabletop', 'portugal'],
            ],
            [
                'name' => 'Filipe Costa Gaming',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@FilipeCosta',
                'instagram' => '@filipecostagaming',
                'niche' => 'rpg,adventure,soulslike',
                'subscribers' => 55000,
                'avg_views' => 7000,
                'engagement_rate' => 6.3,
                'status' => 'prospect',
                'tags' => ['rpg', 'aventura', 'soulslike', 'portugal'],
            ],

            // ── REVIEW / ANÁLISE ────────────────────────────────────────────
            [
                'name' => 'Crítica Gamer PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@CriticaGamerPT',
                'instagram' => '@criticagamerpt',
                'niche' => 'game_review,analysis,critique',
                'subscribers' => 92000,
                'avg_views' => 11500,
                'engagement_rate' => 6.0,
                'status' => 'prospect',
                'tags' => ['review', 'análise', 'crítica', 'portugal'],
            ],
            [
                'name' => 'Gameplay Portugal',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@GameplayPortugal',
                'instagram' => '@gameplayportugal',
                'niche' => 'game_review,letsplay,general_gaming',
                'subscribers' => 168000,
                'avg_views' => 20000,
                'engagement_rate' => 5.4,
                'status' => 'prospect',
                'tags' => ['review', 'let\'s play', 'gaming', 'portugal'],
            ],
            [
                'name' => 'Gamer Reviews PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@GamerReviewsPT',
                'instagram' => '@gamerreviews.pt',
                'niche' => 'game_review,indie,aaa',
                'subscribers' => 78000,
                'avg_views' => 9800,
                'engagement_rate' => 5.8,
                'status' => 'prospect',
                'tags' => ['review', 'indie', 'AAA', 'portugal'],
            ],
            [
                'name' => 'Análise de Jogos',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@AnaliseDeJogosPT',
                'instagram' => '@analisedejogos',
                'niche' => 'game_review,analysis,critique',
                'subscribers' => 66000,
                'avg_views' => 8500,
                'engagement_rate' => 6.1,
                'status' => 'prospect',
                'tags' => ['análise', 'review', 'crítica', 'portugal'],
            ],
            [
                'name' => 'GameStar PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@GameStarPT',
                'instagram' => '@gamestarpt',
                'niche' => 'game_review,tech,hardware',
                'subscribers' => 82000,
                'avg_views' => 10200,
                'engagement_rate' => 5.6,
                'status' => 'prospect',
                'tags' => ['review', 'tech', 'hardware', 'portugal'],
            ],
            [
                'name' => 'Pixel Review PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@PixelReviewPT',
                'instagram' => '@pixelreviewpt',
                'niche' => 'indie,game_review,pixel_art',
                'subscribers' => 48000,
                'avg_views' => 6200,
                'engagement_rate' => 6.5,
                'status' => 'prospect',
                'tags' => ['indie', 'review', 'pixel art', 'portugal'],
            ],

            // ── RETRO / CULTURA GAMER ────────────────────────────────────────
            [
                'name' => 'Retrogamer PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@RetrogamerPT',
                'instagram' => '@retrogamerpt',
                'niche' => 'retro,history,review',
                'subscribers' => 72000,
                'avg_views' => 9200,
                'engagement_rate' => 6.2,
                'status' => 'prospect',
                'tags' => ['retro', 'história', 'clássicos', 'portugal'],
            ],
            [
                'name' => 'Jogos de Antigamente PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@JogosDeAntigamentePT',
                'instagram' => '@jogosantigamente.pt',
                'niche' => 'retro,nostalgia,review',
                'subscribers' => 58000,
                'avg_views' => 7500,
                'engagement_rate' => 6.4,
                'status' => 'prospect',
                'tags' => ['retro', 'nostalgia', 'clássicos', 'portugal'],
            ],
            [
                'name' => 'Portugal Gamer Cultura',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@PortugalGamerCultura',
                'instagram' => '@portugalgamercultura',
                'niche' => 'gaming_culture,documentary,history',
                'subscribers' => 44000,
                'avg_views' => 5800,
                'engagement_rate' => 6.3,
                'status' => 'prospect',
                'tags' => ['cultura gamer', 'documentário', 'história', 'portugal'],
            ],
            [
                'name' => 'Console Wars PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@ConsoleWarsPT',
                'instagram' => '@consolewarspt',
                'niche' => 'retro,console,history',
                'subscribers' => 38000,
                'avg_views' => 5000,
                'engagement_rate' => 6.1,
                'status' => 'prospect',
                'tags' => ['retro', 'console', 'história', 'portugal'],
            ],
            [
                'name' => 'Geek Palace PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@GeekPalacePT',
                'instagram' => '@geekpalacept',
                'niche' => 'geek,gaming_culture,movies',
                'subscribers' => 95000,
                'avg_views' => 12000,
                'engagement_rate' => 5.9,
                'status' => 'prospect',
                'tags' => ['geek', 'cultura', 'filmes', 'games', 'portugal'],
            ],

            // ── TECH / HARDWARE / PC GAMING ─────────────────────────────────
            [
                'name' => 'PCMaster PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@PCMasterPT',
                'instagram' => '@pcmasterpt',
                'niche' => 'hardware,tech,pc_gaming',
                'subscribers' => 142000,
                'avg_views' => 18000,
                'engagement_rate' => 5.3,
                'status' => 'prospect',
                'tags' => ['hardware', 'tech', 'PC gaming', 'portugal'],
            ],
            [
                'name' => 'Setup Gamer PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@SetupGamerPT',
                'instagram' => '@setupgamerpt',
                'niche' => 'hardware,setup,tech',
                'subscribers' => 88000,
                'avg_views' => 11000,
                'engagement_rate' => 5.5,
                'status' => 'prospect',
                'tags' => ['setup', 'hardware', 'tech', 'portugal'],
            ],
            [
                'name' => 'Benchmark PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@BenchmarkPT',
                'instagram' => '@benchmarkpt',
                'niche' => 'hardware,benchmarks,pc_gaming',
                'subscribers' => 76000,
                'avg_views' => 9500,
                'engagement_rate' => 5.2,
                'status' => 'prospect',
                'tags' => ['benchmark', 'hardware', 'PC gaming', 'portugal'],
            ],
            [
                'name' => 'Geek It PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@GeekItPT',
                'instagram' => '@geekitpt',
                'niche' => 'tech,gaming,tutorials',
                'subscribers' => 63000,
                'avg_views' => 8000,
                'engagement_rate' => 5.7,
                'status' => 'prospect',
                'tags' => ['tech', 'gaming', 'tutoriais', 'portugal'],
            ],

            // ── MOBILE / CASUAL ─────────────────────────────────────────────
            [
                'name' => 'Mobile Gamer PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@MobileGamerPT',
                'instagram' => '@mobilegamerpt',
                'niche' => 'mobile,casual,tips',
                'subscribers' => 108000,
                'avg_views' => 13500,
                'engagement_rate' => 5.8,
                'status' => 'prospect',
                'tags' => ['mobile', 'casual', 'dicas', 'portugal'],
            ],
            [
                'name' => 'Clash PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@ClashPT',
                'instagram' => '@clashpt',
                'niche' => 'mobile,strategy,clash',
                'subscribers' => 92000,
                'avg_views' => 11500,
                'engagement_rate' => 5.6,
                'status' => 'prospect',
                'tags' => ['mobile', 'estratégia', 'clash royale', 'portugal'],
            ],
            [
                'name' => 'PT Gamer Mobile',
                'type' => 'tiktok',
                'channel_url' => 'https://www.tiktok.com/@ptgamermobile',
                'instagram' => '@ptgamermobile',
                'niche' => 'mobile,clips,tiktok',
                'subscribers' => 185000,
                'avg_views' => 45000,
                'engagement_rate' => 8.5,
                'status' => 'prospect',
                'tags' => ['mobile', 'clips', 'tiktok', 'portugal'],
            ],

            // ── INSTAGRAM / INFLUENCERS GAMING ──────────────────────────────
            [
                'name' => 'Joana Gamer PT',
                'type' => 'instagram',
                'channel_url' => 'https://www.instagram.com/joanagamerpt',
                'instagram' => '@joanagamerpt',
                'niche' => 'gaming,lifestyle,cosplay',
                'subscribers' => 132000,
                'avg_views' => 15000,
                'engagement_rate' => 6.8,
                'status' => 'prospect',
                'tags' => ['gaming', 'cosplay', 'lifestyle', 'feminino', 'portugal'],
            ],
            [
                'name' => 'Gamer Girl PT',
                'type' => 'instagram',
                'channel_url' => 'https://www.instagram.com/gamergirl.pt',
                'instagram' => '@gamergirl.pt',
                'niche' => 'gaming,fashion,lifestyle',
                'subscribers' => 98000,
                'avg_views' => 12000,
                'engagement_rate' => 7.0,
                'status' => 'prospect',
                'tags' => ['gaming', 'lifestyle', 'fashion', 'feminino', 'portugal'],
            ],
            [
                'name' => 'GamesBR_PT',
                'type' => 'instagram',
                'channel_url' => 'https://www.instagram.com/gamesbr_pt',
                'instagram' => '@gamesbr_pt',
                'niche' => 'gaming,memes,culture',
                'subscribers' => 225000,
                'avg_views' => 28000,
                'engagement_rate' => 7.2,
                'status' => 'prospect',
                'tags' => ['gaming', 'memes', 'cultura', 'portugal'],
            ],
            [
                'name' => 'Gamer Lusitano',
                'type' => 'instagram',
                'channel_url' => 'https://www.instagram.com/gamerlusitano',
                'instagram' => '@gamerlusitano',
                'niche' => 'gaming,culture,history',
                'subscribers' => 76000,
                'avg_views' => 9500,
                'engagement_rate' => 6.5,
                'status' => 'prospect',
                'tags' => ['gaming', 'cultura', 'lusitano', 'portugal'],
            ],

            // ── ESPORTS PORTUGAL ─────────────────────────────────────────────
            [
                'name' => 'SL Benfica Esports',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@BenficaEsports',
                'instagram' => '@benficaesports',
                'twitter' => '@BenficaEsports',
                'niche' => 'esports,fps,lol',
                'subscribers' => 48000,
                'avg_views' => 6200,
                'engagement_rate' => 5.5,
                'status' => 'prospect',
                'tags' => ['esports', 'benfica', 'portugal', 'fps', 'lol'],
            ],
            [
                'name' => 'Sporting CP Esports',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@SportingEsports',
                'instagram' => '@sportingcpesports',
                'twitter' => '@SportingEsports',
                'niche' => 'esports,fps,general_gaming',
                'subscribers' => 38000,
                'avg_views' => 5000,
                'engagement_rate' => 5.8,
                'status' => 'prospect',
                'tags' => ['esports', 'sporting', 'portugal'],
            ],
            [
                'name' => 'FC Porto Esports',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@FCPortoEsports',
                'instagram' => '@fcportoesports',
                'niche' => 'esports,fps,general_gaming',
                'subscribers' => 32000,
                'avg_views' => 4200,
                'engagement_rate' => 5.6,
                'status' => 'prospect',
                'tags' => ['esports', 'porto', 'portugal'],
            ],
            [
                'name' => 'Esports Portugal',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@EsportsPortugal',
                'instagram' => '@esportsportugal',
                'twitter' => '@EsportsPortugal',
                'niche' => 'esports,news,general_gaming',
                'subscribers' => 55000,
                'avg_views' => 7000,
                'engagement_rate' => 5.9,
                'status' => 'prospect',
                'tags' => ['esports', 'news', 'portugal'],
            ],
            [
                'name' => 'Portugal Gaming League',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@PortugalGamingLeague',
                'instagram' => '@portugalgamingleague',
                'niche' => 'esports,tournament,fps',
                'subscribers' => 42000,
                'avg_views' => 5500,
                'engagement_rate' => 6.0,
                'status' => 'prospect',
                'tags' => ['esports', 'torneio', 'portugal'],
            ],

            // ── PODCAST / TALK ───────────────────────────────────────────────
            [
                'name' => 'Gaming Podcast PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@GamingPodcastPT',
                'instagram' => '@gamingpodcastpt',
                'niche' => 'podcast,gaming_culture,talk',
                'subscribers' => 68000,
                'avg_views' => 8500,
                'engagement_rate' => 6.2,
                'status' => 'prospect',
                'tags' => ['podcast', 'cultura gamer', 'portugal'],
            ],
            [
                'name' => 'Game Over PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@GameOverPT',
                'instagram' => '@gameoverpt',
                'niche' => 'podcast,review,gaming_culture',
                'subscribers' => 54000,
                'avg_views' => 7000,
                'engagement_rate' => 6.0,
                'status' => 'prospect',
                'tags' => ['podcast', 'review', 'cultura gamer', 'portugal'],
            ],
            [
                'name' => 'Bits & Bytes PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@BitsAndBytesPT',
                'instagram' => '@bitsbytest.pt',
                'niche' => 'tech,gaming,podcast',
                'subscribers' => 46000,
                'avg_views' => 6000,
                'engagement_rate' => 6.3,
                'status' => 'prospect',
                'tags' => ['tech', 'gaming', 'podcast', 'portugal'],
            ],
            [
                'name' => 'Nerd Talk PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@NerdTalkPT',
                'instagram' => '@nerdtalkpt',
                'niche' => 'geek,gaming,movies,talk',
                'subscribers' => 38000,
                'avg_views' => 5000,
                'engagement_rate' => 6.1,
                'status' => 'prospect',
                'tags' => ['geek', 'gaming', 'filmes', 'podcast', 'portugal'],
            ],

            // ── MAIS CRIADORES PT ────────────────────────────────────────────
            [
                'name' => 'GK47 Portugal',
                'type' => 'streamer',
                'channel_url' => 'https://www.youtube.com/@GK47Portugal',
                'instagram' => '@gk47portugal',
                'niche' => 'fps,valorant,cs2',
                'subscribers' => 72000,
                'avg_views' => 9000,
                'engagement_rate' => 5.8,
                'status' => 'prospect',
                'tags' => ['valorant', 'cs2', 'fps', 'portugal'],
            ],
            [
                'name' => 'xGamerPT',
                'type' => 'streamer',
                'channel_url' => 'https://www.youtube.com/@xGamerPT',
                'instagram' => '@xgamerpt',
                'niche' => 'general_gaming,fps,streaming',
                'subscribers' => 61000,
                'avg_views' => 7800,
                'engagement_rate' => 5.9,
                'status' => 'prospect',
                'tags' => ['gaming', 'fps', 'streaming', 'portugal'],
            ],
            [
                'name' => 'ProGamer Lisboa',
                'type' => 'streamer',
                'channel_url' => 'https://www.youtube.com/@ProGamerLisboa',
                'instagram' => '@progamerlisboa',
                'niche' => 'esports,fps,competitive',
                'subscribers' => 53000,
                'avg_views' => 6800,
                'engagement_rate' => 6.1,
                'status' => 'prospect',
                'tags' => ['esports', 'fps', 'competitivo', 'lisboa'],
            ],
            [
                'name' => 'Estrelas Gaming PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@EstrelasGamingPT',
                'instagram' => '@estrelasgamingpt',
                'niche' => 'general_gaming,family,kids',
                'subscribers' => 88000,
                'avg_views' => 11000,
                'engagement_rate' => 5.7,
                'status' => 'prospect',
                'tags' => ['gaming', 'família', 'kids', 'portugal'],
            ],
            [
                'name' => 'Indie Dev PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@IndieDevPT',
                'instagram' => '@indiedevpt',
                'niche' => 'indie,game_dev,devlog',
                'subscribers' => 29000,
                'avg_views' => 4000,
                'engagement_rate' => 7.8,
                'status' => 'prospect',
                'tags' => ['indie', 'devlog', 'game dev', 'portugal'],
            ],
            [
                'name' => 'Miguel Lopes Games',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@MiguelLopesGames',
                'instagram' => '@miguellopesgames',
                'niche' => 'general_gaming,review,tips',
                'subscribers' => 44000,
                'avg_views' => 5600,
                'engagement_rate' => 5.8,
                'status' => 'prospect',
                'tags' => ['gaming', 'review', 'dicas', 'portugal'],
            ],
            [
                'name' => 'Sofia Gamer PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@SofiaGamerPT',
                'instagram' => '@sofiagamerpt',
                'niche' => 'general_gaming,variety,lifestyle',
                'subscribers' => 67000,
                'avg_views' => 8500,
                'engagement_rate' => 6.4,
                'status' => 'prospect',
                'tags' => ['gaming', 'variedades', 'lifestyle', 'feminino', 'portugal'],
            ],
            [
                'name' => 'Game Arena PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@GameArenaPT',
                'instagram' => '@gamearenapt',
                'niche' => 'general_gaming,esports,tournament',
                'subscribers' => 58000,
                'avg_views' => 7400,
                'engagement_rate' => 5.9,
                'status' => 'prospect',
                'tags' => ['gaming', 'esports', 'torneio', 'portugal'],
            ],
            [
                'name' => 'Funny Games PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@FunnyGamesPT',
                'instagram' => '@funnygamespt',
                'niche' => 'comedy,gaming,clips',
                'subscribers' => 115000,
                'avg_views' => 14500,
                'engagement_rate' => 5.6,
                'status' => 'prospect',
                'tags' => ['humor', 'gaming', 'clips', 'portugal'],
            ],
            [
                'name' => 'Level Up PT',
                'type' => 'youtuber',
                'channel_url' => 'https://www.youtube.com/@LevelUpPT',
                'instagram' => '@leveluppt',
                'niche' => 'general_gaming,tips,guides',
                'subscribers' => 103000,
                'avg_views' => 13000,
                'engagement_rate' => 5.5,
                'status' => 'prospect',
                'tags' => ['gaming', 'dicas', 'guias', 'portugal'],
            ],
        ];

        foreach ($influencers as $data) {
            $data['user_id'] = $userId;
            $data['country'] = 'Portugal';
            $data['language'] = 'Portuguese';
            if (isset($data['tags']) && is_array($data['tags'])) {
                $data['tags'] = json_encode($data['tags']);
            }
            if (isset($data['games_covered']) && is_array($data['games_covered'])) {
                $data['games_covered'] = json_encode($data['games_covered']);
            }
            Influencer::create($data);
        }
    }
}
